all:
	gcc -Wall -g3 -c trydate.c
	gcc -Wall -g3 -c tryls.c
	gcc -Wall -g3 -c trycat.c
	gcc -Wall -g3 -c trymkdir.c
	gcc -Wall -g3 -c tryrm.c

	gcc -o trydate trydate.o
	gcc -o tryls tryls.o
	gcc -o trycat trycat.o
	gcc -o trymkdir trymkdir.o
	gcc -o tryrm tryrm.o

	gcc -Wall -g3 -c shell.c
	gcc -o shell shell.o


